//! Board profiles: which devkit the chip sits on, and what each header pin is.
//!
//! Ported from the `bancada-idf` sibling (its `core/src/boards.rs`), unchanged:
//! this is pure data plus pure functions grounded in chip physics, so it is
//! paradigm-agnostic — the pin-safety and board facts apply the same whether a
//! project is built with `arduino-cli` or `idf.py`. The `docs/boards/*.md`
//! pages are a vendored snapshot generated by the sibling's `bidf board <id>
//! --markdown`; [`render_markdown`] reproduces them byte for byte here so the
//! doc test keeps them honest without a Bancada regeneration command (a
//! `board` command will front this once the toolchain abstraction lands).
//!
//! [`targets`](crate::targets) knows the *chip*. This module knows the
//! *board* — the headers, the silkscreen labels, the onboard LED and BOOT
//! button, the USB ports, and a closed vocabulary of caveats per GPIO
//! (strapping, input-only, flash, native USB, UART0 console, JTAG, ADC2 vs
//! Wi-Fi). It exists so every frontend — the CLI, the window, the assistant —
//! answers "which pin is the LED" and "is GPIO12 safe" from one table.
//!
//! ## Why this table is the authority, unlike `targets.rs`
//!
//! `idf.py` has no board concept. There is no engine to ask and no "a newer
//! IDF may know it" escape hatch, so an id not in [`KNOWN_BOARDS`] is not a
//! board this build knows — full stop — and [`Board::from_id`] returning
//! `None` is an error the caller reports, not a hint to pass the id along.
//!
//! ## Where a row's facts come from
//!
//! Chip-level facts (strapping pins, USB pins, …) live once per SoC in
//! [`SOC_PINS`]; each row repeats the ones that apply so the table reads as
//! documentation, and `every_row_agrees_with_its_chip` keeps the two from
//! drifting. Board-level facts (header order, labels, LED, BOOT, USB ports)
//! are transcribed from the vendor's user guide, whose URL is in
//! [`Board::sources`]; the DOIT board has no vendor guide, so its rows were
//! read off the silkscreen and checked against the physical board.
//!
//! ## The chosen board is remembered in `sdkconfig.defaults`
//!
//! As the comment line [`BOARD_MARKER`]` <id>`. A comment, not a `CONFIG_`
//! key: ESP-IDF's kconfgen prints a note for every unknown symbol on every
//! reconfigure, while a comment is silent, survives `fullclean` (which
//! regenerates `sdkconfig`, not `sdkconfig.defaults`), and travels with the
//! repository. [`read_marker`], [`set_marker`] and [`clear_marker`] are pure
//! transforms over the file's text; `IdfProject::board` does the I/O.
//!
//! ## The docs are generated from this table
//!
//! [`render_markdown`] produces `docs/boards/<id>.md`, and a test asserts the
//! checked-in page equals it byte for byte. Regenerate with
//! `bidf board <id> --markdown > docs/boards/<id>.md`.

use serde::Serialize;

/// Something to know before using a pin. Closed set, so frontends can render
/// it and the assistant can explain it without parsing prose.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum Caveat {
    /// The level at reset selects the boot mode.
    Strapping,
    /// Classic ESP32 GPIO34–39: no output driver, no internal pulls.
    InputOnly,
    /// Wired to the module's SPI flash or PSRAM on some module variants.
    FlashOrPsram,
    /// Native USB D−/D+; reconfiguring disables USB-Serial/JTAG.
    UsbSerialJtag,
    /// UART0 — the USB-UART bridge and the default console use it.
    Uart0Console,
    /// A JTAG signal (MTMS/MTDI/MTCK/MTDO) by default.
    Jtag,
    /// ADC2 cannot be read while Wi-Fi is on.
    Adc2WifiConflict,
    /// Drives the onboard LED.
    OnboardLed,
    /// The BOOT button pulls it low.
    BootButton,
}

impl Caveat {
    pub const ALL: &'static [Caveat] = &[
        Caveat::Strapping,
        Caveat::InputOnly,
        Caveat::FlashOrPsram,
        Caveat::UsbSerialJtag,
        Caveat::Uart0Console,
        Caveat::Jtag,
        Caveat::Adc2WifiConflict,
        Caveat::OnboardLed,
        Caveat::BootButton,
    ];

    /// Fragment register: a badge, a table cell, a status line.
    pub fn label(self) -> &'static str {
        match self {
            Caveat::Strapping => "strapping pin",
            Caveat::InputOnly => "input only",
            Caveat::FlashOrPsram => "flash/PSRAM",
            Caveat::UsbSerialJtag => "native USB",
            Caveat::Uart0Console => "UART0 console",
            Caveat::Jtag => "JTAG",
            Caveat::Adc2WifiConflict => "ADC2 — not with Wi-Fi",
            Caveat::OnboardLed => "onboard LED",
            Caveat::BootButton => "BOOT button",
        }
    }

    /// Prose register: what to do about it.
    pub fn advice(self) -> &'static str {
        match self {
            Caveat::Strapping => {
                "The level at reset selects the boot mode. Leave it at its default during \
                 reset; a pull-up or pull-down on it changes how the chip boots."
            }
            Caveat::InputOnly => {
                "Input only. It cannot drive an output and has no internal pull-up or \
                 pull-down."
            }
            Caveat::FlashOrPsram => {
                "Wired to the module's SPI flash or PSRAM on some module variants. Using it \
                 as GPIO corrupts memory access on those modules."
            }
            Caveat::UsbSerialJtag => {
                "Native USB D-/D+. Reconfiguring it as a GPIO disables USB-Serial/JTAG, and \
                 with it the USB port."
            }
            Caveat::Uart0Console => {
                "UART0. The USB-UART bridge and the default console log use it; driving it \
                 as GPIO garbles the console."
            }
            Caveat::Jtag => "A JTAG signal by default. Free to use if you do not debug over JTAG.",
            Caveat::Adc2WifiConflict => {
                "An ADC2 channel. ADC2 cannot be read while Wi-Fi is on; use an ADC1 pin for \
                 analog input alongside Wi-Fi."
            }
            Caveat::OnboardLed => "Drives the onboard LED. Free to use, but the LED follows it.",
            Caveat::BootButton => {
                "The BOOT button pulls it low. Free to use as an input after boot; holding it \
                 low through a reset enters the bootloader."
            }
        }
    }
}

/// One glossary entry, for a frontend that wants the labels once rather than
/// a lookup per badge.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct CaveatInfo {
    pub id: Caveat,
    pub label: &'static str,
    pub advice: &'static str,
}

pub fn caveat_glossary() -> Vec<CaveatInfo> {
    Caveat::ALL
        .iter()
        .map(|&c| CaveatInfo {
            id: c,
            label: c.label(),
            advice: c.advice(),
        })
        .collect()
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum LedKind {
    /// A plain LED: toggling the pin lights it.
    Plain,
    /// An addressable WS2812: needs a data stream, a plain toggle does nothing.
    Ws2812,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub struct Led {
    pub gpio: u8,
    pub kind: LedKind,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(tag = "kind", rename_all = "kebab-case")]
pub enum UsbKind {
    /// A USB-UART bridge chip between the connector and UART0.
    Bridge { chip: &'static str },
    /// The SoC's own USB-Serial/JTAG peripheral on D−/D+.
    Native,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub struct UsbPort {
    /// What the silkscreen calls it: "UART", "USB", or just "USB" when there is one.
    pub label: &'static str,
    pub kind: UsbKind,
    /// The GPIOs the port occupies: UART0 TX/RX for a bridge, D−/D+ for native.
    pub gpios: &'static [u8],
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum Side {
    Left,
    Right,
}

/// One physical pin position, top to bottom with the USB connector at the bottom.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub struct HeaderPin {
    /// The silkscreen label: "D34", "TX0", "3V3", "G", "NC".
    pub label: &'static str,
    /// `None` for power, ground, reset and no-connect rows.
    pub gpio: Option<u8>,
    /// Alternate functions worth knowing: "ADC1_CH6", "U0TXD", "MTMS", …
    pub functions: &'static [&'static str],
    pub caveats: &'static [Caveat],
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub struct Header {
    /// The silkscreen name: "J1", "J3"; the DOIT board has none, so "left"/"right".
    pub name: &'static str,
    pub side: Side,
    pub pins: &'static [HeaderPin],
}

/// One known board.
///
/// `Serialize` only, for the same reason as [`crate::targets::Target`]: every
/// value is a borrow of [`KNOWN_BOARDS`], so a caller reading one back from
/// JSON wants [`Board::from_id`] on the id, not a deserialized copy.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub struct Board {
    /// Stable kebab-case id: "esp32-s3-devkitc-1".
    pub id: &'static str,
    /// The vendor's name for it: "ESP32-S3-DevKitC-1".
    pub name: &'static str,
    pub vendor: &'static str,
    /// A `KNOWN_TARGETS` id.
    pub target: &'static str,
    pub revision: &'static str,
    pub module: &'static str,
    pub usb: &'static [UsbPort],
    pub led: Option<Led>,
    /// The GPIO the BOOT button pulls low.
    pub boot_button: Option<u8>,
    pub headers: &'static [Header],
    /// Where the rows were transcribed from.
    pub sources: &'static [&'static str],
    /// Quirks worth a sentence: revisions, module variants.
    pub notes: &'static [&'static str],
}

/// Chip-level pin facts, once per SoC. Rows repeat the ones that apply; the
/// test `every_row_agrees_with_its_chip` keeps them honest.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SocPins {
    pub target: &'static str,
    pub strapping: &'static [u8],
    pub input_only: &'static [u8],
    pub flash_or_psram: &'static [u8],
    pub usb: &'static [u8],
    pub uart0: &'static [u8],
    pub jtag: &'static [u8],
    pub adc2: &'static [u8],
}

impl SocPins {
    pub fn for_target(target: &str) -> Option<&'static SocPins> {
        SOC_PINS.iter().find(|s| s.target == target)
    }
}

/// From the ESP-IDF GPIO summary tables and the SoC datasheets.
pub const SOC_PINS: &[SocPins] = &[
    SocPins {
        target: "esp32",
        strapping: &[0, 2, 5, 12, 15],
        input_only: &[34, 35, 36, 37, 38, 39],
        flash_or_psram: &[6, 7, 8, 9, 10, 11],
        usb: &[],
        uart0: &[1, 3],
        jtag: &[12, 13, 14, 15],
        adc2: &[0, 2, 4, 12, 13, 14, 15, 25, 26, 27],
    },
    SocPins {
        target: "esp32s3",
        strapping: &[0, 3, 45, 46],
        input_only: &[],
        // 26–32 are the SPI flash; 33–37 are SPIIO4–7/SPIDQS on octal
        // flash/PSRAM modules (R8, R8V).
        flash_or_psram: &[26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37],
        usb: &[19, 20],
        uart0: &[43, 44],
        jtag: &[39, 40, 41, 42],
        adc2: &[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    },
    SocPins {
        target: "esp32c6",
        strapping: &[4, 5, 8, 9, 15],
        input_only: &[],
        flash_or_psram: &[24, 25, 26, 27, 28, 29, 30],
        usb: &[12, 13],
        uart0: &[16, 17],
        jtag: &[4, 5, 6, 7],
        // The C6 has ADC1 only.
        adc2: &[],
    },
];

const S: Caveat = Caveat::Strapping;
const IO: Caveat = Caveat::InputOnly;
const FL: Caveat = Caveat::FlashOrPsram;
const USB: Caveat = Caveat::UsbSerialJtag;
const U0: Caveat = Caveat::Uart0Console;
const JT: Caveat = Caveat::Jtag;
const A2: Caveat = Caveat::Adc2WifiConflict;
const LED: Caveat = Caveat::OnboardLed;
const BOOT: Caveat = Caveat::BootButton;

const fn power(label: &'static str) -> HeaderPin {
    HeaderPin {
        label,
        gpio: None,
        functions: &[],
        caveats: &[],
    }
}

const fn gpio(
    label: &'static str,
    n: u8,
    functions: &'static [&'static str],
    caveats: &'static [Caveat],
) -> HeaderPin {
    HeaderPin {
        label,
        gpio: Some(n),
        functions,
        caveats,
    }
}

/// Every board this build knows. See the module docs for why this is the
/// authority and not a fallback.
pub const KNOWN_BOARDS: &[Board] = &[
    // ------------------------------------------------------- ESP32-S3-DevKitC-1
    Board {
        id: "esp32-s3-devkitc-1",
        name: "ESP32-S3-DevKitC-1",
        vendor: "Espressif",
        target: "esp32s3",
        revision: "v1.1",
        module: "ESP32-S3-WROOM-1 / WROOM-1U (N8R8, N16R8, …) or WROOM-2",
        usb: &[
            UsbPort {
                label: "UART",
                kind: UsbKind::Bridge { chip: "CP2102N" },
                gpios: &[43, 44],
            },
            UsbPort {
                label: "USB",
                kind: UsbKind::Native,
                gpios: &[19, 20],
            },
        ],
        led: Some(Led {
            gpio: 38,
            kind: LedKind::Ws2812,
        }),
        boot_button: Some(0),
        headers: &[
            Header {
                name: "J1",
                side: Side::Left,
                pins: &[
                    power("3V3"),
                    power("3V3"),
                    power("RST"),
                    gpio("4", 4, &["RTC_GPIO4", "TOUCH4", "ADC1_CH3"], &[]),
                    gpio("5", 5, &["RTC_GPIO5", "TOUCH5", "ADC1_CH4"], &[]),
                    gpio("6", 6, &["RTC_GPIO6", "TOUCH6", "ADC1_CH5"], &[]),
                    gpio("7", 7, &["RTC_GPIO7", "TOUCH7", "ADC1_CH6"], &[]),
                    gpio("15", 15, &["RTC_GPIO15", "U0RTS", "ADC2_CH4", "XTAL_32K_P"], &[A2]),
                    gpio("16", 16, &["RTC_GPIO16", "U0CTS", "ADC2_CH5", "XTAL_32K_N"], &[A2]),
                    gpio("17", 17, &["RTC_GPIO17", "U1TXD", "ADC2_CH6"], &[A2]),
                    gpio("18", 18, &["RTC_GPIO18", "U1RXD", "ADC2_CH7", "CLK_OUT3"], &[A2]),
                    gpio("8", 8, &["RTC_GPIO8", "TOUCH8", "ADC1_CH7", "SUBSPICS1"], &[]),
                    gpio("3", 3, &["RTC_GPIO3", "TOUCH3", "ADC1_CH2"], &[S]),
                    gpio("46", 46, &[], &[S]),
                    gpio(
                        "9",
                        9,
                        &["RTC_GPIO9", "TOUCH9", "ADC1_CH8", "FSPIHD", "SUBSPIHD"],
                        &[],
                    ),
                    gpio(
                        "10",
                        10,
                        &["RTC_GPIO10", "TOUCH10", "ADC1_CH9", "FSPICS0", "FSPIIO4", "SUBSPICS0"],
                        &[],
                    ),
                    gpio(
                        "11",
                        11,
                        &["RTC_GPIO11", "TOUCH11", "ADC2_CH0", "FSPID", "FSPIIO5", "SUBSPID"],
                        &[A2],
                    ),
                    gpio(
                        "12",
                        12,
                        &["RTC_GPIO12", "TOUCH12", "ADC2_CH1", "FSPICLK", "FSPIIO6", "SUBSPICLK"],
                        &[A2],
                    ),
                    gpio(
                        "13",
                        13,
                        &["RTC_GPIO13", "TOUCH13", "ADC2_CH2", "FSPIQ", "FSPIIO7", "SUBSPIQ"],
                        &[A2],
                    ),
                    gpio(
                        "14",
                        14,
                        &["RTC_GPIO14", "TOUCH14", "ADC2_CH3", "FSPIWP", "FSPIDQS", "SUBSPIWP"],
                        &[A2],
                    ),
                    power("5V"),
                    power("G"),
                ],
            },
            Header {
                name: "J3",
                side: Side::Right,
                pins: &[
                    power("G"),
                    gpio("TX", 43, &["U0TXD", "CLK_OUT1"], &[U0]),
                    gpio("RX", 44, &["U0RXD", "CLK_OUT2"], &[U0]),
                    gpio("1", 1, &["RTC_GPIO1", "TOUCH1", "ADC1_CH0"], &[]),
                    gpio("2", 2, &["RTC_GPIO2", "TOUCH2", "ADC1_CH1"], &[]),
                    gpio("42", 42, &["MTMS"], &[JT]),
                    gpio("41", 41, &["MTDI", "CLK_OUT1"], &[JT]),
                    gpio("40", 40, &["MTDO", "CLK_OUT2"], &[JT]),
                    gpio("39", 39, &["MTCK", "CLK_OUT3", "SUBSPICS1"], &[JT]),
                    gpio("38", 38, &["FSPIWP", "SUBSPIWP", "RGB LED"], &[LED]),
                    gpio("37", 37, &["SPIDQS", "FSPIQ", "SUBSPIQ"], &[FL]),
                    gpio("36", 36, &["SPIIO7", "FSPICLK", "SUBSPICLK"], &[FL]),
                    gpio("35", 35, &["SPIIO6", "FSPID", "SUBSPID"], &[FL]),
                    gpio("0", 0, &["RTC_GPIO0", "BOOT"], &[S, BOOT]),
                    gpio("45", 45, &[], &[S]),
                    gpio("48", 48, &["SPICLK_N", "SUBSPICLK_N_DIFF"], &[]),
                    gpio("47", 47, &["SPICLK_P", "SUBSPICLK_P_DIFF"], &[]),
                    gpio("21", 21, &["RTC_GPIO21"], &[]),
                    gpio(
                        "20",
                        20,
                        &["RTC_GPIO20", "U1CTS", "ADC2_CH9", "CLK_OUT1", "USB_D+"],
                        &[USB, A2],
                    ),
                    gpio(
                        "19",
                        19,
                        &["RTC_GPIO19", "U1RTS", "ADC2_CH8", "CLK_OUT2", "USB_D-"],
                        &[USB, A2],
                    ),
                    power("G"),
                    power("G"),
                ],
            },
        ],
        sources: &[
            "https://docs.espressif.com/projects/esp-dev-kits/en/latest/esp32s3/esp32-s3-devkitc-1/user_guide_v1.1.html",
            "https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-reference/peripherals/gpio.html",
        ],
        notes: &[
            "v1.0 boards drive the RGB LED from GPIO48; v1.1 moved it to GPIO38.",
            "GPIO35, GPIO36 and GPIO37 are used by octal flash/PSRAM on R8 and R8V modules and are not available for external use there; they are free on quad-only modules.",
        ],
    },
    // ------------------------------------------------------- ESP32-C6-DevKitC-1
    Board {
        id: "esp32-c6-devkitc-1",
        name: "ESP32-C6-DevKitC-1",
        vendor: "Espressif",
        target: "esp32c6",
        revision: "v1.2",
        module: "ESP32-C6-WROOM-1 / WROOM-1U",
        usb: &[
            UsbPort {
                label: "UART",
                kind: UsbKind::Bridge { chip: "CP2102N" },
                gpios: &[16, 17],
            },
            UsbPort {
                label: "USB",
                kind: UsbKind::Native,
                gpios: &[12, 13],
            },
        ],
        led: Some(Led {
            gpio: 8,
            kind: LedKind::Ws2812,
        }),
        boot_button: Some(9),
        headers: &[
            Header {
                name: "J1",
                side: Side::Left,
                pins: &[
                    power("3V3"),
                    power("RST"),
                    gpio(
                        "4",
                        4,
                        &["MTMS", "LP_GPIO4", "LP_UART_RXD", "ADC1_CH4", "FSPIHD"],
                        &[S, JT],
                    ),
                    gpio(
                        "5",
                        5,
                        &["MTDI", "LP_GPIO5", "LP_UART_TXD", "ADC1_CH5", "FSPIWP"],
                        &[S, JT],
                    ),
                    gpio(
                        "6",
                        6,
                        &["MTCK", "LP_GPIO6", "LP_I2C_SDA", "ADC1_CH6", "FSPICLK"],
                        &[JT],
                    ),
                    gpio("7", 7, &["MTDO", "LP_GPIO7", "LP_I2C_SCL", "FSPID"], &[JT]),
                    gpio(
                        "0",
                        0,
                        &["XTAL_32K_P", "LP_GPIO0", "LP_UART_DTRN", "ADC1_CH0"],
                        &[],
                    ),
                    gpio(
                        "1",
                        1,
                        &["XTAL_32K_N", "LP_GPIO1", "LP_UART_DSRN", "ADC1_CH1"],
                        &[],
                    ),
                    gpio("8", 8, &["RGB LED"], &[S, LED]),
                    gpio("10", 10, &[], &[]),
                    gpio("11", 11, &[], &[]),
                    gpio("2", 2, &["LP_GPIO2", "LP_UART_RTSN", "ADC1_CH2", "FSPIQ"], &[]),
                    gpio("3", 3, &["LP_GPIO3", "LP_UART_CTSN", "ADC1_CH3"], &[]),
                    power("5V"),
                    power("G"),
                    power("NC"),
                ],
            },
            Header {
                name: "J3",
                side: Side::Right,
                pins: &[
                    power("G"),
                    gpio("TX", 16, &["U0TXD", "FSPICS0"], &[U0]),
                    gpio("RX", 17, &["U0RXD", "FSPICS1"], &[U0]),
                    gpio("15", 15, &[], &[S]),
                    gpio("23", 23, &["SDIO_DATA3"], &[]),
                    gpio("22", 22, &["SDIO_DATA2"], &[]),
                    gpio("21", 21, &["SDIO_DATA1", "FSPICS5"], &[]),
                    gpio("20", 20, &["SDIO_DATA0", "FSPICS4"], &[]),
                    gpio("19", 19, &["SDIO_CLK", "FSPICS3"], &[]),
                    gpio("18", 18, &["SDIO_CMD", "FSPICS2"], &[]),
                    gpio("9", 9, &["BOOT"], &[S, BOOT]),
                    power("G"),
                    gpio("13", 13, &["USB_D+"], &[USB]),
                    gpio("12", 12, &["USB_D-"], &[USB]),
                    power("G"),
                    power("NC"),
                ],
            },
        ],
        sources: &[
            "https://docs.espressif.com/projects/esp-dev-kits/en/latest/esp32c6/esp32-c6-devkitc-1/user_guide.html",
            "https://docs.espressif.com/projects/esp-idf/en/latest/esp32c6/api-reference/peripherals/gpio.html",
        ],
        notes: &[
            "The SPI bus to the module's flash (GPIO24–30) is not broken out.",
            "GPIO14 is not available on the WROOM-1 module and is not on the headers.",
        ],
    },
    // ---------------------------------------------------- DOIT ESP32 DEVKIT V1
    Board {
        id: "esp32-doit-devkit-v1",
        name: "DOIT ESP32 DEVKIT V1",
        vendor: "DOIT",
        target: "esp32",
        revision: "30-pin",
        module: "ESP32-WROOM-32",
        usb: &[UsbPort {
            label: "USB",
            kind: UsbKind::Bridge { chip: "CP2102" },
            gpios: &[1, 3],
        }],
        led: Some(Led {
            gpio: 2,
            kind: LedKind::Plain,
        }),
        boot_button: Some(0),
        headers: &[
            Header {
                name: "left",
                side: Side::Left,
                pins: &[
                    power("EN"),
                    gpio("VP", 36, &["ADC1_CH0", "SENSOR_VP"], &[IO]),
                    gpio("VN", 39, &["ADC1_CH3", "SENSOR_VN"], &[IO]),
                    gpio("D34", 34, &["ADC1_CH6"], &[IO]),
                    gpio("D35", 35, &["ADC1_CH7"], &[IO]),
                    gpio("D32", 32, &["ADC1_CH4", "TOUCH9", "XTAL_32K_P"], &[]),
                    gpio("D33", 33, &["ADC1_CH5", "TOUCH8", "XTAL_32K_N"], &[]),
                    gpio("D25", 25, &["ADC2_CH8", "DAC_1"], &[A2]),
                    gpio("D26", 26, &["ADC2_CH9", "DAC_2"], &[A2]),
                    gpio("D27", 27, &["ADC2_CH7", "TOUCH7"], &[A2]),
                    gpio("D14", 14, &["ADC2_CH6", "TOUCH6", "MTMS", "HSPICLK"], &[JT, A2]),
                    gpio("D12", 12, &["ADC2_CH5", "TOUCH5", "MTDI", "HSPIQ"], &[S, JT, A2]),
                    gpio("D13", 13, &["ADC2_CH4", "TOUCH4", "MTCK", "HSPID"], &[JT, A2]),
                    power("GND"),
                    power("VIN"),
                ],
            },
            Header {
                name: "right",
                side: Side::Right,
                pins: &[
                    gpio("D23", 23, &["VSPID (MOSI)"], &[]),
                    gpio("D22", 22, &["VSPIWP", "I2C SCL (default)"], &[]),
                    gpio("TX0", 1, &["U0TXD"], &[U0]),
                    gpio("RX0", 3, &["U0RXD"], &[U0]),
                    gpio("D21", 21, &["VSPIHD", "I2C SDA (default)"], &[]),
                    gpio("D19", 19, &["VSPIQ (MISO)"], &[]),
                    gpio("D18", 18, &["VSPICLK"], &[]),
                    gpio("D5", 5, &["VSPICS0"], &[S]),
                    gpio("TX2", 17, &["U2TXD"], &[]),
                    gpio("RX2", 16, &["U2RXD"], &[]),
                    gpio("D4", 4, &["ADC2_CH0", "TOUCH0"], &[A2]),
                    gpio("D2", 2, &["ADC2_CH2", "TOUCH2", "HSPIWP", "LED"], &[S, A2, LED]),
                    gpio("D15", 15, &["ADC2_CH3", "TOUCH3", "MTDO", "HSPICS0"], &[S, JT, A2]),
                    power("GND"),
                    power("3V3"),
                ],
            },
        ],
        sources: &[
            "the board's silkscreen, checked against the physical board (no vendor user guide exists)",
            "https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/gpio.html",
        ],
        notes: &[
            "The BOOT button pulls GPIO0 low; GPIO0 itself is not on the headers.",
            "GPIO6–11 are the module's SPI flash and are not broken out on the 30-pin board (the 36-pin variant exposes them; they are still unusable).",
            "GPIO36/39 are labelled VP/VN on the silkscreen.",
        ],
    },
];

impl Board {
    /// Look up a canonical id. `None` means "not a board this build knows" —
    /// there is no engine to defer to, so the caller reports it.
    pub fn from_id(id: &str) -> Option<&'static Board> {
        KNOWN_BOARDS.iter().find(|b| b.id == id)
    }

    /// Look up by any human spelling: case, spaces and underscores are folded
    /// into the kebab-case id.
    pub fn lookup(input: &str) -> Option<&'static Board> {
        let id = input.trim().to_ascii_lowercase().replace(['_', ' '], "-");
        Board::from_id(&id)
    }

    /// The row for a GPIO, if the board breaks it out.
    pub fn pin(&self, gpio: u8) -> Option<&'static HeaderPin> {
        // `self` is always a borrow of KNOWN_BOARDS, so the rows are 'static;
        // going through the table makes the borrow checker agree.
        KNOWN_BOARDS
            .iter()
            .find(|b| b.id == self.id)?
            .headers
            .iter()
            .flat_map(|h| h.pins.iter())
            .find(|p| p.gpio == Some(gpio))
    }
}

/// The boards built around a target, by any spelling of the target.
pub fn boards_for_target(target: &str) -> Vec<&'static Board> {
    let id = crate::targets::normalize_id(target);
    KNOWN_BOARDS.iter().filter(|b| b.target == id).collect()
}

/// What [`check_pin`] says about a GPIO.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(tag = "kind", rename_all = "kebab-case")]
pub enum PinVerdict {
    /// Not on any header — flash pins, unbonded pins, or a number this chip
    /// does not have. Same answer either way: you cannot wire to it.
    NotBrokenOut,
    Free,
    Caution {
        caveats: Vec<Caveat>,
    },
}

/// The pin-safety policy. `bidf pin`, the Board tab and the assistant's
/// `board_pinout` all call this and nothing else.
pub fn check_pin(board: &Board, gpio: u8) -> PinVerdict {
    match board.pin(gpio) {
        None => PinVerdict::NotBrokenOut,
        Some(p) if p.caveats.is_empty() => PinVerdict::Free,
        Some(p) => PinVerdict::Caution {
            caveats: p.caveats.to_vec(),
        },
    }
}

/// The line that remembers the board in `sdkconfig.defaults`. A comment on
/// purpose — see the module docs.
pub const BOARD_MARKER: &str = "# bancada.board = ";

/// Parse one line as a marker. Forgives spacing around `#`, the key and `=`.
fn marker_value(line: &str) -> Option<&str> {
    let rest = line.trim().strip_prefix('#')?.trim_start();
    let rest = rest.strip_prefix("bancada.board")?.trim_start();
    let value = rest.strip_prefix('=')?.trim();
    (!value.is_empty()).then_some(value)
}

fn is_marker_line(line: &str) -> bool {
    line.trim()
        .strip_prefix('#')
        .map(str::trim_start)
        .is_some_and(|r| r.starts_with("bancada.board"))
}

/// The board id the text names, if any. The first marker wins.
pub fn read_marker(text: &str) -> Option<String> {
    text.lines().find_map(marker_value).map(str::to_string)
}

/// The text with the marker set to `id`: replaced in place when one exists
/// (any further markers are dropped), appended on its own line otherwise.
/// Always ends with a newline, so the next `CONFIG_` line a tool appends
/// starts cleanly.
pub fn set_marker(text: &str, id: &str) -> String {
    let marker = format!("{BOARD_MARKER}{id}");
    let mut out = String::new();
    let mut placed = false;
    for line in text.lines() {
        if is_marker_line(line) {
            if !placed {
                out.push_str(&marker);
                out.push('\n');
                placed = true;
            }
            continue;
        }
        out.push_str(line);
        out.push('\n');
    }
    if !placed {
        out.push_str(&marker);
        out.push('\n');
    }
    out
}

/// The text without any marker line. Everything else is kept byte for byte,
/// including the presence or absence of a trailing newline.
pub fn clear_marker(text: &str) -> String {
    if !text.lines().any(is_marker_line) {
        return text.to_string();
    }
    let mut out: String = text
        .lines()
        .filter(|l| !is_marker_line(l))
        .map(|l| format!("{l}\n"))
        .collect();
    if !text.ends_with('\n') && !out.is_empty() {
        out.pop();
    }
    out
}

/// The board as a two-column box: left header down the left edge, right
/// header down the right edge, USB at the bottom. Box-drawing only.
pub fn render_layout(board: &Board) -> String {
    let labels = |side: Side| -> Vec<&'static str> {
        board
            .headers
            .iter()
            .filter(|h| h.side == side)
            .flat_map(|h| h.pins.iter().map(|p| p.label))
            .collect()
    };
    let left = labels(Side::Left);
    let right = labels(Side::Right);
    let w = left.iter().map(|s| s.len()).max().unwrap_or(0).max(3);
    let rows = left.len().max(right.len());
    let inner = "        ";
    let mut out = String::new();
    out.push_str(&format!(
        "{:>w$}  ┌{}┐\n",
        "",
        "─".repeat(inner.len()),
        w = w
    ));
    for i in 0..rows {
        let l = left.get(i).copied().unwrap_or("");
        let r = right.get(i).copied().unwrap_or("");
        let lj = if l.is_empty() { " │" } else { "─┤" };
        let rj = if r.is_empty() { "│ " } else { "├─" };
        out.push_str(&format!("{l:>w$} {lj}{inner}{rj} {r}\n", w = w));
    }
    let usb: Vec<&str> = board.usb.iter().map(|u| u.label).collect();
    let foot = format!("USB: {}", usb.join(" / "));
    out.push_str(&format!(
        "{:>w$}  └{}┘\n",
        "",
        "─".repeat(inner.len()),
        w = w
    ));
    out.push_str(&format!("{:>w$}    {foot}\n", "", w = w));
    out
}

/// `docs/boards/<id>.md`. The checked-in page must equal this byte for byte;
/// `every_board_page_matches_the_table` enforces it.
pub fn render_markdown(board: &Board) -> String {
    let target = crate::targets::Target::from_id(board.target);
    let mut md = String::new();
    md.push_str(&format!("# {} ({})\n\n", board.name, board.revision));
    md.push_str("<!-- generated by `bidf board ");
    md.push_str(board.id);
    md.push_str(" --markdown` from core/src/boards.rs — do not edit by hand -->\n\n");

    md.push_str("| | |\n|---|---|\n");
    md.push_str(&format!("| id | `{}` |\n", board.id));
    md.push_str(&format!("| vendor | {} |\n", board.vendor));
    md.push_str(&format!("| module | {} |\n", board.module));
    md.push_str(&format!(
        "| target | `{}`{} |\n",
        board.target,
        target
            .map(|t| format!(" ({}, {})", t.name, t.arch.label()))
            .unwrap_or_default()
    ));
    for u in board.usb {
        let what = match u.kind {
            UsbKind::Bridge { chip } => format!("{chip} USB-UART bridge"),
            UsbKind::Native => "native USB-Serial/JTAG".to_string(),
        };
        let pins: Vec<String> = u.gpios.iter().map(|g| format!("GPIO{g}")).collect();
        md.push_str(&format!(
            "| USB \"{}\" | {what} → {} |\n",
            u.label,
            pins.join(", ")
        ));
    }
    match board.led {
        Some(Led {
            gpio,
            kind: LedKind::Plain,
        }) => md.push_str(&format!("| LED | plain LED on GPIO{gpio} |\n")),
        Some(Led {
            gpio,
            kind: LedKind::Ws2812,
        }) => md.push_str(&format!("| LED | WS2812 addressable LED on GPIO{gpio} |\n")),
        None => md.push_str("| LED | none |\n"),
    }
    match board.boot_button {
        Some(g) => md.push_str(&format!("| BOOT button | GPIO{g} |\n")),
        None => md.push_str("| BOOT button | none |\n"),
    }
    md.push('\n');

    md.push_str("## Layout\n\nUSB connector at the bottom, components facing you.\n\n```\n");
    md.push_str(&render_layout(board));
    md.push_str("```\n\n");

    let mut used: Vec<Caveat> = Vec::new();
    for h in board.headers {
        let side = match h.side {
            Side::Left => "left",
            Side::Right => "right",
        };
        md.push_str(&format!("## {} ({side}, top to bottom)\n\n", h.name));
        md.push_str("| # | label | GPIO | functions | caveats |\n|---|---|---|---|---|\n");
        for (i, p) in h.pins.iter().enumerate() {
            let gpio = p
                .gpio
                .map(|g| g.to_string())
                .unwrap_or_else(|| "—".to_string());
            let caveats: Vec<&str> = p.caveats.iter().map(|c| c.label()).collect();
            for c in p.caveats {
                if !used.contains(c) {
                    used.push(*c);
                }
            }
            md.push_str(&format!(
                "| {} | {} | {gpio} | {} | {} |\n",
                i + 1,
                p.label,
                p.functions.join(", "),
                caveats.join(", ")
            ));
        }
        md.push('\n');
    }

    if !used.is_empty() {
        md.push_str("## Caveats on this board\n\n");
        for c in Caveat::ALL.iter().filter(|c| used.contains(c)) {
            md.push_str(&format!("- **{}** — {}\n", c.label(), c.advice()));
        }
        md.push('\n');
    }

    if !board.notes.is_empty() {
        md.push_str("## Notes\n\n");
        for n in board.notes {
            md.push_str(&format!("- {n}\n"));
        }
        md.push('\n');
    }

    md.push_str("## Sources\n\n");
    for s in board.sources {
        md.push_str(&format!("- {s}\n"));
    }
    md
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_board_targets_a_chip_this_build_knows() {
        for b in KNOWN_BOARDS {
            assert!(
                crate::targets::Target::from_id(b.target).is_some(),
                "{} names target {:?}, which is not in KNOWN_TARGETS",
                b.id,
                b.target
            );
        }
    }

    #[test]
    fn every_board_id_is_kebab_case_and_unique() {
        let mut seen = std::collections::HashSet::new();
        for b in KNOWN_BOARDS {
            assert!(
                b.id.chars()
                    .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-'),
                "{:?} is not kebab-case",
                b.id
            );
            assert!(seen.insert(b.id), "{:?} appears twice", b.id);
        }
    }

    #[test]
    fn a_gpio_is_on_a_board_at_most_once() {
        for b in KNOWN_BOARDS {
            let mut seen = std::collections::HashSet::new();
            for h in b.headers {
                for p in h.pins {
                    if let Some(g) = p.gpio {
                        assert!(seen.insert(g), "{}: GPIO{g} is listed twice", b.id);
                    }
                }
            }
        }
    }

    #[test]
    fn the_led_is_on_a_header() {
        // The BOOT button is allowed off the header (the DOIT board's GPIO0 is
        // a button only), but an LED pin a user cannot reach is a table error.
        for b in KNOWN_BOARDS {
            if let Some(led) = &b.led {
                assert!(
                    b.pin(led.gpio).is_some(),
                    "{}: LED GPIO{} is not on any header",
                    b.id,
                    led.gpio
                );
            }
        }
    }

    #[test]
    fn every_row_agrees_with_its_chip() {
        // The chip-level caveats are derived facts. A row may not claim or omit
        // one the SoC table disagrees with — that is how a typo like marking
        // GPIO38 strapping on the S3 gets caught.
        for b in KNOWN_BOARDS {
            let soc = SocPins::for_target(b.target)
                .unwrap_or_else(|| panic!("{}: no SOC_PINS entry for {}", b.id, b.target));
            for h in b.headers {
                for p in h.pins {
                    let Some(g) = p.gpio else { continue };
                    let expect = |c: Caveat, list: &[u8]| {
                        assert_eq!(
                            p.caveats.contains(&c),
                            list.contains(&g),
                            "{}: GPIO{g} and {:?} disagree with SOC_PINS",
                            b.id,
                            c
                        );
                    };
                    expect(Caveat::Strapping, soc.strapping);
                    expect(Caveat::InputOnly, soc.input_only);
                    expect(Caveat::FlashOrPsram, soc.flash_or_psram);
                    expect(Caveat::UsbSerialJtag, soc.usb);
                    expect(Caveat::Uart0Console, soc.uart0);
                    expect(Caveat::Jtag, soc.jtag);
                    expect(Caveat::Adc2WifiConflict, soc.adc2);
                    assert_eq!(
                        p.caveats.contains(&Caveat::OnboardLed),
                        b.led.as_ref().is_some_and(|l| l.gpio == g),
                        "{}: GPIO{g} OnboardLed disagrees with Board.led",
                        b.id
                    );
                    assert_eq!(
                        p.caveats.contains(&Caveat::BootButton),
                        b.boot_button == Some(g),
                        "{}: GPIO{g} BootButton disagrees with Board.boot_button",
                        b.id
                    );
                }
            }
        }
    }

    #[test]
    fn every_caveat_has_a_fragment_label_and_a_prose_advice() {
        for c in Caveat::ALL {
            let label = c.label();
            assert!(
                !label.is_empty() && !label.ends_with('.'),
                "{c:?} label {label:?}"
            );
            // Fragments are lower case — except that an acronym stays an
            // acronym: "UART0 console", "JTAG", "BOOT button".
            let first_word = label.split_whitespace().next().unwrap();
            assert!(
                label.chars().next().unwrap().is_lowercase()
                    || first_word
                        .chars()
                        .all(|c| c.is_ascii_uppercase() || c.is_ascii_digit()),
                "{c:?} label {label:?}"
            );
            let advice = c.advice();
            assert!(advice.ends_with('.'), "{c:?} advice {advice:?}");
            assert!(
                advice.chars().next().unwrap().is_uppercase(),
                "{c:?} advice {advice:?}"
            );
        }
        assert_eq!(caveat_glossary().len(), Caveat::ALL.len());
    }

    #[test]
    fn the_s3_devkitc_1_v1_1_led_is_gpio38_and_the_usb_pins_are_19_and_20() {
        let b = KNOWN_BOARDS
            .iter()
            .find(|b| b.id == "esp32-s3-devkitc-1")
            .unwrap();
        assert_eq!(b.target, "esp32s3");
        assert_eq!(
            b.led.as_ref().map(|l| (l.gpio, l.kind)),
            Some((38, LedKind::Ws2812))
        );
        assert_eq!(b.boot_button, Some(0));
        assert_eq!(b.headers.len(), 2);
        assert_eq!(b.headers[0].pins.len(), 22);
        assert_eq!(b.headers[1].pins.len(), 22);
        let native = b.usb.iter().find(|u| u.kind == UsbKind::Native).unwrap();
        assert_eq!(native.gpios, &[19, 20]);
        assert!(b.pin(38).unwrap().caveats.contains(&Caveat::OnboardLed));
        assert!(b.pin(0).unwrap().caveats.contains(&Caveat::Strapping));
        assert!(b.pin(35).unwrap().caveats.contains(&Caveat::FlashOrPsram));
    }

    #[test]
    fn the_c6_devkitc_1_led_is_gpio8_and_boot_is_gpio9() {
        let b = KNOWN_BOARDS
            .iter()
            .find(|b| b.id == "esp32-c6-devkitc-1")
            .unwrap();
        assert_eq!(b.target, "esp32c6");
        assert_eq!(
            b.led.as_ref().map(|l| (l.gpio, l.kind)),
            Some((8, LedKind::Ws2812))
        );
        assert_eq!(b.boot_button, Some(9));
        assert_eq!(b.headers[0].pins.len(), 16);
        assert_eq!(b.headers[1].pins.len(), 16);
        assert!(b.pin(12).unwrap().caveats.contains(&Caveat::UsbSerialJtag));
        assert!(b.pin(16).unwrap().caveats.contains(&Caveat::Uart0Console));
        assert!(b.pin(4).unwrap().caveats.contains(&Caveat::Jtag));
        assert!(
            b.pin(14).is_none(),
            "GPIO14 is not on the C6 DevKitC-1 headers"
        );
    }

    #[test]
    fn the_doit_devkit_v1_has_30_pins_a_plain_led_on_gpio2_and_no_flash_pins_broken_out() {
        let b = KNOWN_BOARDS
            .iter()
            .find(|b| b.id == "esp32-doit-devkit-v1")
            .unwrap();
        assert_eq!(b.target, "esp32");
        assert_eq!(
            b.led.as_ref().map(|l| (l.gpio, l.kind)),
            Some((2, LedKind::Plain))
        );
        assert_eq!(b.boot_button, Some(0));
        assert_eq!(b.headers[0].pins.len() + b.headers[1].pins.len(), 30);
        assert!(
            b.pin(0).is_none(),
            "BOOT is a button, not a header pin, on this board"
        );
        for flash in 6..=11 {
            assert!(
                b.pin(flash).is_none(),
                "GPIO{flash} is flash and not broken out"
            );
        }
        assert!(b.pin(34).unwrap().caveats.contains(&Caveat::InputOnly));
        assert!(b.pin(12).unwrap().caveats.contains(&Caveat::Strapping));
        assert!(b
            .pin(25)
            .unwrap()
            .caveats
            .contains(&Caveat::Adc2WifiConflict));
    }

    #[test]
    fn there_are_exactly_three_boards_for_now() {
        let ids: Vec<&str> = KNOWN_BOARDS.iter().map(|b| b.id).collect();
        assert_eq!(
            ids,
            [
                "esp32-s3-devkitc-1",
                "esp32-c6-devkitc-1",
                "esp32-doit-devkit-v1"
            ]
        );
    }

    #[test]
    fn from_id_is_exact_and_lookup_forgives_case_spaces_and_underscores() {
        assert!(Board::from_id("esp32-s3-devkitc-1").is_some());
        assert!(Board::from_id("ESP32-S3-DevKitC-1").is_none());
        assert_eq!(
            Board::lookup(" ESP32_S3 DevKitC-1 ").map(|b| b.id),
            Some("esp32-s3-devkitc-1")
        );
        assert!(Board::lookup("esp32-s3-devkitc-9").is_none());
        assert!(Board::lookup("").is_none());
    }

    #[test]
    fn boards_for_target_filters_by_chip_and_accepts_any_spelling() {
        let s3: Vec<&str> = boards_for_target("ESP32-S3").iter().map(|b| b.id).collect();
        assert_eq!(s3, ["esp32-s3-devkitc-1"]);
        assert!(boards_for_target("esp32h2").is_empty());
    }

    #[test]
    fn check_pin_says_free_caution_or_not_broken_out() {
        let s3 = Board::from_id("esp32-s3-devkitc-1").unwrap();
        assert_eq!(check_pin(s3, 4), PinVerdict::Free);
        assert_eq!(
            check_pin(s3, 0),
            PinVerdict::Caution {
                caveats: vec![Caveat::Strapping, Caveat::BootButton]
            }
        );
        assert_eq!(
            check_pin(s3, 26),
            PinVerdict::NotBrokenOut,
            "flash pin, not on a header"
        );
        assert_eq!(
            check_pin(s3, 99),
            PinVerdict::NotBrokenOut,
            "no such GPIO at all"
        );

        let doit = Board::from_id("esp32-doit-devkit-v1").unwrap();
        assert_eq!(check_pin(doit, 6), PinVerdict::NotBrokenOut);
        assert_eq!(check_pin(doit, 23), PinVerdict::Free);
    }

    #[test]
    fn a_verdict_serializes_with_a_kind_tag_the_frontend_can_switch_on() {
        let v = serde_json::to_value(check_pin(Board::from_id("esp32-s3-devkitc-1").unwrap(), 19))
            .unwrap();
        assert_eq!(v["kind"], "caution");
        assert_eq!(v["caveats"][0], "usb-serial-jtag");
        let free = serde_json::to_value(PinVerdict::Free).unwrap();
        assert_eq!(free, serde_json::json!({"kind": "free"}));
    }

    #[test]
    fn the_marker_round_trips_through_an_empty_file() {
        let text = set_marker("", "esp32-c6-devkitc-1");
        assert_eq!(text, "# bancada.board = esp32-c6-devkitc-1\n");
        assert_eq!(read_marker(&text).as_deref(), Some("esp32-c6-devkitc-1"));
        assert_eq!(clear_marker(&text), "");
    }

    #[test]
    fn the_marker_is_replaced_in_place_and_everything_else_is_untouched() {
        let before = "CONFIG_LOG_DEFAULT_LEVEL=3\n# bancada.board = esp32-doit-devkit-v1\n# CONFIG_X is not set\n";
        let after = set_marker(before, "esp32-s3-devkitc-1");
        assert_eq!(
            after,
            "CONFIG_LOG_DEFAULT_LEVEL=3\n# bancada.board = esp32-s3-devkitc-1\n# CONFIG_X is not set\n"
        );
    }

    #[test]
    fn the_marker_is_appended_on_its_own_line_even_without_a_trailing_newline() {
        assert_eq!(
            set_marker("CONFIG_A=y", "esp32-s3-devkitc-1"),
            "CONFIG_A=y\n# bancada.board = esp32-s3-devkitc-1\n"
        );
        assert_eq!(
            set_marker("CONFIG_A=y\n", "esp32-s3-devkitc-1"),
            "CONFIG_A=y\n# bancada.board = esp32-s3-devkitc-1\n"
        );
    }

    #[test]
    fn two_markers_collapse_to_one_and_a_malformed_one_reads_as_none() {
        let messy = "# bancada.board = a\nCONFIG_A=y\n# bancada.board = b\n";
        assert_eq!(read_marker(messy).as_deref(), Some("a"), "first wins");
        assert_eq!(set_marker(messy, "c"), "# bancada.board = c\nCONFIG_A=y\n");
        assert_eq!(read_marker("# bancada.board =\n"), None);
        assert_eq!(read_marker("# bancada.board\n"), None);
        assert_eq!(
            read_marker("#bancada.board=x\n").as_deref(),
            Some("x"),
            "spacing is forgiven"
        );
    }

    #[test]
    fn clearing_removes_the_line_and_leaves_the_rest_byte_for_byte() {
        let text = "CONFIG_A=y\n# bancada.board = x\nCONFIG_B=n\n";
        assert_eq!(clear_marker(text), "CONFIG_A=y\nCONFIG_B=n\n");
        assert_eq!(clear_marker("CONFIG_A=y\n"), "CONFIG_A=y\n");
    }

    #[test]
    fn the_layout_puts_the_left_header_on_the_left_and_the_usb_at_the_bottom() {
        let b = Board::from_id("esp32-c6-devkitc-1").unwrap();
        let layout = render_layout(b);
        let first = layout.lines().nth(1).unwrap();
        assert!(first.trim_start().starts_with("3V3"), "{first:?}");
        assert!(first.trim_end().ends_with('G'), "{first:?}");
        assert!(layout.lines().last().unwrap().contains("USB"), "{layout}");
        assert!(
            layout
                .chars()
                .all(|c| c.is_ascii() || "┌┐└┘─│┤├".contains(c)),
            "box-drawing only"
        );
    }

    #[test]
    fn the_page_has_the_facts_the_layout_the_tables_and_the_sources() {
        let b = Board::from_id("esp32-s3-devkitc-1").unwrap();
        let page = render_markdown(b);
        assert!(page.starts_with("# ESP32-S3-DevKitC-1 (v1.1)\n"), "{page}");
        assert!(page.contains("| `esp32-s3-devkitc-1` |"));
        assert!(page.contains("WS2812 addressable LED on GPIO38"));
        assert!(page.contains("## J1 (left, top to bottom)"));
        assert!(page.contains("| 10 | 38 | 38 | FSPIWP, SUBSPIWP, RGB LED | onboard LED |"));
        assert!(page.contains("**strapping pin** — The level at reset"));
        assert!(page.contains("user_guide_v1.1.html"));
        assert!(page.contains("generated by `bidf board esp32-s3-devkitc-1 --markdown`"));
    }

    #[test]
    fn every_board_page_matches_the_table() {
        // The docs are generated from this table; this is the gate that keeps
        // them from drifting. Regenerate with
        //   bidf board <id> --markdown > docs/boards/<id>.md
        let docs = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../docs/boards");
        for b in KNOWN_BOARDS {
            let path = docs.join(format!("{}.md", b.id));
            let on_disk = std::fs::read_to_string(&path).unwrap_or_else(|e| {
                panic!(
                    "{}: {e} — generate it with `bidf board {} --markdown`",
                    path.display(),
                    b.id
                )
            });
            assert_eq!(
                on_disk,
                render_markdown(b),
                "{} is out of date — regenerate with `bidf board {} --markdown > {}`",
                path.display(),
                b.id,
                path.display()
            );
        }
    }
}
